export type DiagnosticLayer =
  | 'core'
  | 'application'
  | 'infrastructure'
  | 'composition'
  | 'boundary'
  | 'ui'
  | 'testing'
  | 'tool';

export type DiagnosticRule = {
  code: string;
  severity: 'error' | 'warn' | 'info' | 'mixed';
  layer: DiagnosticLayer;
  stability: 'stable' | 'experimental';
  fixable: boolean;
  description: string;
};

export const diagnosticRegistry: DiagnosticRule[] = [
  {
    code: 'ai/emoji-in-code',
    severity: 'error',
    layer: 'ui',
    stability: 'experimental',
    fixable: true,
    description: 'Source files should not contain emoji characters.',
  },
  {
    code: 'ai/mock-in-core',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Core code must not contain mock implementations.',
  },
  {
    code: 'ai/mock-placement',
    severity: 'warn',
    layer: 'testing',
    stability: 'experimental',
    fixable: true,
    description: 'Mock files should live under infrastructure/mocks.',
  },
  {
    code: 'ai/proactive-readme',
    severity: 'warn',
    layer: 'composition',
    stability: 'experimental',
    fixable: true,
    description: 'Module README files are treated as proactive documentation drift.',
  },
  {
    code: 'arch/adapter-missing-implements',
    severity: 'error',
    layer: 'infrastructure',
    stability: 'stable',
    fixable: true,
    description: 'Adapters should implement a port interface.',
  },
  {
    code: 'arch/adapter-missing-port-import',
    severity: 'error',
    layer: 'infrastructure',
    stability: 'stable',
    fixable: true,
    description: 'Adapters should import port interfaces from application/ports or core/ports.',
  },
  {
    code: 'arch/forbidden-folder-core-adapters',
    severity: 'error',
    layer: 'core',
    stability: 'stable',
    fixable: true,
    description: 'Adapters must not live under core/adapters.',
  },
  {
    code: 'arch/forbidden-folder-core-rules',
    severity: 'error',
    layer: 'core',
    stability: 'stable',
    fixable: true,
    description: 'Application policies must not live under core/rules.',
  },
  {
    code: 'arch/forbidden-folder-core-use-cases',
    severity: 'error',
    layer: 'core',
    stability: 'stable',
    fixable: true,
    description: 'Use cases must not live under core/use-cases.',
  },
  {
    code: 'arch/forbidden-folder-db',
    severity: 'error',
    layer: 'infrastructure',
    stability: 'stable',
    fixable: true,
    description: 'Module db folders should be replaced by infrastructure/persistence.',
  },
  {
    code: 'arch/forbidden-folder-server',
    severity: 'error',
    layer: 'boundary',
    stability: 'stable',
    fixable: true,
    description: 'Module server folders should be replaced by boundary or infrastructure adapters.',
  },
  {
    code: 'arch/forbidden-folder-types',
    severity: 'error',
    layer: 'core',
    stability: 'stable',
    fixable: true,
    description: 'Top-level module types folders should be colocated with their owning layer.',
  },
  {
    code: 'arch/missing-application-folder',
    severity: 'error',
    layer: 'application',
    stability: 'stable',
    fixable: true,
    description: 'A module is missing application/.',
  },
  {
    code: 'arch/missing-composition-folder',
    severity: 'error',
    layer: 'composition',
    stability: 'stable',
    fixable: true,
    description: 'A module is missing composition/.',
  },
  {
    code: 'arch/missing-core-folder',
    severity: 'error',
    layer: 'core',
    stability: 'stable',
    fixable: true,
    description: 'A module is missing core/.',
  },
  {
    code: 'arch/missing-infrastructure-folder',
    severity: 'error',
    layer: 'infrastructure',
    stability: 'stable',
    fixable: true,
    description: 'A module is missing infrastructure/.',
  },
  {
    code: 'architecture/no-cross-module-infrastructure',
    severity: 'error',
    layer: 'infrastructure',
    stability: 'stable',
    fixable: true,
    description: 'Infrastructure code must not import another module infrastructure layer.',
  },
  {
    code: 'ast/core-imports-forbidden',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Core code must not import forbidden runtime dependencies.',
  },
  {
    code: 'ast/core-side-effect',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Core code must not perform runtime side effects.',
  },
  {
    code: 'ast/manual-literal-union',
    severity: 'warn',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Manual literal unions should reuse canonical domain sets.',
  },
  {
    code: 'ast/views-missing-schema-import',
    severity: 'warn',
    layer: 'infrastructure',
    stability: 'experimental',
    fixable: true,
    description: 'View schemas should import their backing persistence schema.',
  },
  {
    code: 'composition/cli-entrypoint-forbidden',
    severity: 'error',
    layer: 'composition',
    stability: 'stable',
    fixable: true,
    description: 'Runtime code must not import .cli entrypoints.',
  },
  {
    code: 'composition/direct-instantiation',
    severity: 'error',
    layer: 'composition',
    stability: 'stable',
    fixable: true,
    description: 'App routes should use composition factories instead of directly instantiating adapters.',
  },
  {
    code: 'composition/factory-naming',
    severity: 'error',
    layer: 'composition',
    stability: 'stable',
    fixable: true,
    description: 'Composition factory functions should use accepted factory naming.',
  },
  {
    code: 'composition/missing-cli-counterpart',
    severity: 'error',
    layer: 'infrastructure',
    stability: 'stable',
    fixable: true,
    description: 'Persistence combined.ts files need a combined.cli.ts counterpart.',
  },
  {
    code: 'composition/no-barrels',
    severity: 'error',
    layer: 'composition',
    stability: 'stable',
    fixable: true,
    description: 'Hexagonal module index barrels are forbidden.',
  },
  {
    code: 'composition/server-actions',
    severity: 'error',
    layer: 'boundary',
    stability: 'stable',
    fixable: true,
    description: 'Server Action files must use a use server directive as the first statement.',
  },
  {
    code: 'composition/server-only-placement',
    severity: 'error',
    layer: 'composition',
    stability: 'stable',
    fixable: true,
    description: 'server-only must be the first import in pure server modules.',
  },
  {
    code: 'composition/server-only-required',
    severity: 'error',
    layer: 'composition',
    stability: 'stable',
    fixable: true,
    description: 'Pure server modules must import server-only before other imports.',
  },
  {
    code: 'contracts/missing',
    severity: 'warn',
    layer: 'testing',
    stability: 'stable',
    fixable: true,
    description: 'Application ports should have contract tests.',
  },
  {
    code: 'contracts/summary',
    severity: 'info',
    layer: 'testing',
    stability: 'stable',
    fixable: false,
    description: 'Contract test coverage summary.',
  },
  {
    code: 'dependency-cruiser-output-snippet',
    severity: 'info',
    layer: 'composition',
    stability: 'stable',
    fixable: false,
    description: 'Snippet emitted when dependency-cruiser output cannot be parsed.',
  },
  {
    code: 'dependency-cruiser-parse-error',
    severity: 'error',
    layer: 'composition',
    stability: 'stable',
    fixable: false,
    description: 'dependency-cruiser output must be parseable as JSON.',
  },
  {
    code: 'domain/optional-undefined',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Optional domain members should not redundantly union with undefined.',
  },
  {
    code: 'domain/return-undefined',
    severity: 'warn',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Domain code should avoid returning bare undefined.',
  },
  {
    code: 'domain/undefined-union',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Exported domain types should avoid undefined unions.',
  },
  {
    code: 'domain/view-input-cast',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Domain views should avoid _input casts.',
  },
  {
    code: 'domain/z-unknown',
    severity: 'warn',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Domain view schemas should prefer explicit shapes over z.unknown().',
  },
  {
    code: 'drizzle/direct-db-return',
    severity: 'warn',
    layer: 'infrastructure',
    stability: 'experimental',
    fixable: true,
    description: 'Database query results should be parsed through views before returning.',
  },
  {
    code: 'drizzle/legacy-adapter',
    severity: 'error',
    layer: 'infrastructure',
    stability: 'experimental',
    fixable: true,
    description: 'Legacy server db adapter imports should be replaced by module-owned helpers.',
  },
  {
    code: 'drizzle/manual-z-object',
    severity: 'warn',
    layer: 'infrastructure',
    stability: 'experimental',
    fixable: true,
    description: 'Drizzle server actions should reuse generated schemas over manual z.object calls.',
  },
  {
    code: 'drizzle/missing-view-parse',
    severity: 'warn',
    layer: 'infrastructure',
    stability: 'experimental',
    fixable: true,
    description: 'Query results should be parsed through a view schema.',
  },
  {
    code: 'drizzle/raw-return',
    severity: 'warn',
    layer: 'infrastructure',
    stability: 'experimental',
    fixable: true,
    description: 'Server actions should not return unparsed success payloads.',
  },
  {
    code: 'drizzle/unvalidated-insert',
    severity: 'warn',
    layer: 'infrastructure',
    stability: 'experimental',
    fixable: true,
    description: 'Insert values should be validated before persistence.',
  },
  {
    code: 'entity/create-returns-result',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Entity factory create methods should return Result.',
  },
  {
    code: 'entity/mutation-returns-result',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Entity mutation methods should return Result.',
  },
  {
    code: 'entity/private-constructor',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Entities should use private constructors with factories.',
  },
  {
    code: 'mocks/missing',
    severity: 'warn',
    layer: 'testing',
    stability: 'stable',
    fixable: true,
    description: 'Application ports should have mock implementations.',
  },
  {
    code: 'mocks/summary',
    severity: 'info',
    layer: 'testing',
    stability: 'stable',
    fixable: false,
    description: 'Mock coverage summary.',
  },
  {
    code: 'result/adapter-missing-try-catch',
    severity: 'warn',
    layer: 'infrastructure',
    stability: 'experimental',
    fixable: true,
    description: 'Adapters should wrap external calls and map failures to Result.',
  },
  {
    code: 'result/no-direct-error-access',
    severity: 'error',
    layer: 'application',
    stability: 'experimental',
    fixable: true,
    description: 'Result error access should be guarded by an error branch.',
  },
  {
    code: 'result/no-error-access',
    severity: 'error',
    layer: 'application',
    stability: 'experimental',
    fixable: true,
    description: 'Result error access should be narrowed before use.',
  },
  {
    code: 'result/no-throw-in-domain',
    severity: 'error',
    layer: 'core',
    stability: 'experimental',
    fixable: true,
    description: 'Core and application layers should return Result instead of throwing.',
  },
  {
    code: 'result/no-value-access',
    severity: 'error',
    layer: 'application',
    stability: 'experimental',
    fixable: true,
    description: 'Result value access should be narrowed before use.',
  },
  {
    code: 'result/unsafe-value-access',
    severity: 'warn',
    layer: 'application',
    stability: 'experimental',
    fixable: true,
    description: 'Regex fallback detected value access without a nearby Result guard.',
  },
  {
    code: 'rsc/forbidden-import',
    severity: 'error',
    layer: 'ui',
    stability: 'experimental',
    fixable: true,
    description: 'Client files must not import server-only modules.',
  },
  {
    code: 'server/action-directive-out-of-place',
    severity: 'error',
    layer: 'boundary',
    stability: 'experimental',
    fixable: true,
    description: 'use server directives must be placed correctly.',
  },
  {
    code: 'server/cache-tags-in-server',
    severity: 'warn',
    layer: 'boundary',
    stability: 'experimental',
    fixable: true,
    description: 'Cache tags should not be declared in server action modules.',
  },
  {
    code: 'server/module-level-use-server',
    severity: 'error',
    layer: 'boundary',
    stability: 'experimental',
    fixable: true,
    description: 'Module-level use server directives are restricted to server action files.',
  },
  {
    code: 'structure/missing',
    severity: 'error',
    layer: 'composition',
    stability: 'stable',
    fixable: true,
    description: 'A module is missing mandatory canonical folders.',
  },
  {
    code: 'structure/optional-missing',
    severity: 'warn',
    layer: 'composition',
    stability: 'stable',
    fixable: true,
    description: 'A module is missing optional canonical folders.',
  },
  {
    code: 'structure/summary',
    severity: 'info',
    layer: 'composition',
    stability: 'stable',
    fixable: false,
    description: 'Canonical module structure summary.',
  },
  {
    code: 'tool/missing-gitleaks',
    severity: 'warn',
    layer: 'tool',
    stability: 'stable',
    fixable: true,
    description: 'The gitleaks binary is not available.',
  },
  {
    code: 'tool/missing-package-script',
    severity: 'error',
    layer: 'tool',
    stability: 'stable',
    fixable: true,
    description: 'A plugin expected a package.json script that does not exist.',
  },
  {
    code: 'validator/required-plugin-skipped',
    severity: 'error',
    layer: 'tool',
    stability: 'stable',
    fixable: true,
    description: 'Strict preset plugins marked as required cannot be skipped.',
  },
];
