/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects and checked in here so
// the example typechecks before `next dev` has ever run.
